### ISSUE TITLE
Offset the play button on the clip video

### ISSUE THREAD

**Issue by ddm999** [fortressforever/fortressforever-web#1]
Seen as the crosshairs where the players are aiming are in the middle of the screen, blocking the place where it all happens with the play button seems a little strange. I think homie's clip on crossover shows this the best, as you can barely see any of what's happening.

Perhaps move it down just a small amount?

**Comment by squeek502** [comment]
It looks pretty strange if it's offset. Lowering the opacity of the play button a bit might be a better option.

**Comment by ddm999** [comment]
Fair enough.
I think so long as you can properly see a ragdoll through it, it should be fine.
( I realise I can just go straight to the .mp4's link to show off FF to friends, but the website is really well made and it'd be a shame to not show it off at the same time :+1: )
