### ISSUE TITLE
Add 2.6.0 changelog

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever-web#3]
Add the [changelog from v2.6.0](http://steamcommunity.com/games/253530/announcements/detail/590349545355147560) to [the changelog page](http://www.fortress-forever.com/changelogs) and a link to the 2.6.0 changelog on [the about page](http://www.fortress-forever.com/about).

**Comment by squeek502** [comment]
Appreciate the reminder. Been meaning to do this for a while. The changelog page is really annoying to update given how much of a mess the file is, though.
