### ISSUE TITLE
Broken stuff in steam browser.

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever-web#4]
Problems are colour of that background (white in other browsers) and video not showing.

Example: ![FF_SteamInGame](https://cloud.githubusercontent.com/assets/11699874/17645746/2aec9a40-61a6-11e6-96cf-372c196e5113.jpg)

**Comment by squeek502** [comment]
Would probably be solved by `body { background-color: #fff; }` being added to the css.
